name: Build and Release Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: [{'name': 'Build executable (jtc-adh-cmd-plus.py)', 'run': 'pyinstaller --onefile jtc-adh-cmd-plus.py'}, {'name': 'Build executable (jtc-adh-cmd-plus2.py)', 'run': 'pyinstaller --onefile jtc-adh-cmd-plus2.py'}, {'name': 'Build executable (jtc-adh-cmd.py)', 'run': 'pyinstaller --onefile jtc-adh-cmd.py'}, {'name': 'Build executable (jtc-adh-easy.py)', 'run': 'pyinstaller --onefile jtc-adh-easy.py'}, {'name': 'Build executable (merge_csv.py)', 'run': 'pyinstaller --onefile merge_csv.py'}, {'name': 'Build executable (scan-to-config.py)', 'run': 'pyinstaller --onefile scan-to-config.py'}, {'name': 'Build executable (split_csv.py)', 'run': 'pyinstaller --onefile split_csv.py'}, {'name': 'Build executable (split_json-adh.py)', 'run': 'pyinstaller --onefile split_json-adh.py'}, {'name': 'Build executable (split_json.py)', 'run': 'pyinstaller --onefile split_json.py'}, {'name': 'Build executable (split_txt.py)', 'run': 'pyinstaller --onefile split_txt.py'}, {'name': 'Build executable (sub-adh.py)', 'run': 'pyinstaller --onefile sub-adh.py'}]
