name: Python Building

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      # 其他步骤...
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller argparse pandas tqdm ijson vaex --ignore-installed
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import argparse --hidden-import pandas --hidden-import os --hidden-import tqdm --hidden-import json --strip jtc-adh-cmd-plus.py --distpath dist/${{ matrix.os }}
          # 其他 pyinstaller 命令...
      # 其他步骤...
      - name: Get latest commit message
        id: get_commit
        run: |
          echo "::set-output name=message::$(git log --format=%B -1)"
      - name: Upload-${{ matrix.os }}-1
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build1-standard-${{ matrix.os }}-1-${{ steps.get_commit.outputs.message }}
          path: dist/${{ matrix.os }}/*

  build-2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      # 其他步骤...
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller argparse pandas tqdm ijson vaex --ignore-installed
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import argparse --hidden-import pandas --hidden-import os --hidden-import tqdm --hidden-import json --strip jtc-adh-cmd-plus2.py --distpath dist/${{ matrix.os }}
          # 其他 pyinstaller 命令...
      # 其他步骤...
      - name: Get latest commit message
        id: get_commit
        run: |
          echo "::set-output name=message::$(git log --format=%B -1)"
      - name: Upload-${{ matrix.os }}-2
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build2-standard-${{ matrix.os }}-2-${{ steps.get_commit.outputs.message }}
          path: dist/${{ matrix.os }}/*
