name: Python Building

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
        script: 
          - jtc-adh-cmd-plus.py
          - jtc-adh-cmd-plus2.py
          - jtc-adh-cmd.py
          - jtc-adh-easy.py
          - merge_csv.py
          - scan-to-config.py
          - split_csv.py
          - split_json-adh.py
          - split_json.py
          - split_txt.py
          - sub-adh.py
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: ${{ matrix.arch }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    # Build executable for each script in the matrix
    - name: Build executable
      run: |
        for file in "${{ matrix.script }}" ; do
            pyinstaller --onefile "$file"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: dist/*

    env:
      ARCH_WINDOWS: 'x64'
      ARCH_UBUNTU: 'x64'

    matrix:
      arch:
        - ${{ env.ARCH_WINDOWS }}
        - ${{ env.ARCH_UBUNTU }}
