name: Python Building Quick

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        architecture: 'x64'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller argparse pandas tqdm ijson vaex --ignore-installed
        pip install -r requirements.txt --ignore-installed
    - name: Build executable
      run: |
        pyinstaller --onefile --hidden-import argparse --hidden-import os --hidden-import vaex --strip jtc-adh-cmd-ultra-vaex.py  --distpath dist/${{ matrix.os }} 

    - name: Get latest commit message
      id: get_commit
      run: |
        echo "::set-output name=message::$(git log --format=%B -1)"

    - name: Upload-${{ matrix.os }}
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}-${{ steps.get_commit.outputs.message }}
        path: dist/${{ matrix.os }}/*